### PR TITLE
fixes for factorio 0.17.35

### PR DESCRIPTION
**Pull request by pditterline**
Changed power-armor-2 references to power-armor-mk2, and changed power-armor-3 to power-armor-mk3 to be consistent with the new name.

I'm not sure how to handle migration (I've never written a mod :) ) so this may break cases where someone has already researched power armor mk3... in my game I only had mk2 researched, and the changes worked there.

### CODE REVIEW

**Comment by jimmyjon711** [comment]
Thanks for doing this, I will look at it and push the change tomorrow.

**Comment by Demolaw** [comment]
i may be wrong but
considered to change the locale/en =>
 [technology-name]
power-armor-mk3=Power Armor Mk3
exoskeleton-mk2-equipment=Exoskeleton Mk2

for adding the proper name for the research inside the techtree instead of the technology.exoskeleton.mk2 handle?

**Comment by Demolaw** [comment]
... hmm github is picky and won't let edit me the last comment, while you are working on it, its no use to fork/ formulate a pull requests while you are being on it ^^'

**Comment by jimmyjon711** [comment]
I guess I could add it for next release. Currently factorio does automatically handle the name, it just shows 2 instead of MK2

**Comment by pditterline** [comment]
I wasn't sure about the name update.. I added the mk3 one because I was getting an undefined key when I looked at the mk3 armor in the tech tree, though that may have been an existing bug.

Sorry the version number broke the in-game portal. :) Thanks for taking my change, and for keeping this mod running!

**Comment by jimmyjon711** [comment]
No worries I didn't think that changing the version would have that effect, but now we know :-)

Also I'm all for others helping out 👍

**Pull request merged**
